project:
  type: website

website:
  title: "Alex Rosen’s Explorations with LLMs"
  description: "Notes, experiments, and mini-essays on LLMs."
  navbar:
    left:
      - text: Blog
        file: index.qmd
      - text: About
        file: about.qmd
  page-footer:
    center: |
      © {{< var year >}} Alex Rosen · Built with [Quarto](https://quarto.org)
  search:
    location: navbar
    type: overlay

format:
  html:
    theme:
      light: litera
      dark: darkly
    toc: true
    toc-location: right
    page-layout: article
    smooth-scroll: true
    code-link: true
    code-copy: true
    highlight-style: a11y
    css: styles.css
    df-print: paged

# Image lightbox on click
filters:
  - lightbox

# Useful site-wide variables
metadata:
  year: 2025

execute:
  freeze: auto
